### PR TITLE
BUG-2067: Update mangopay sdk

### PR DESCRIPTION
**Pull request by meltemkenis**
https://plentific.atlassian.net/browse/BUG-2067
https://plentific.atlassian.net/browse/BUG-2067?focusedCommentId=28255

### CODE REVIEW

**Comment by ciplentific** [comment]
@erenbilaloglu, @lorddex, @selinfildis: please review this pull request.

> Powered by [pull-review](https://github.com/imsky/pull-review)

**Comment by ciplentific** [comment]
@ozerorhun: please review this pull request.

> Powered by [pull-review](https://github.com/imsky/pull-review)

**Review by selinfildis — APPROVED** [review]

**Comment by selinfildis** [comment]
Looks good to me, don't forget to add it as a newly release and test it thoroughly with payments :) 
Here are some general flows to test
- Invoice payment
- updating bank account
- e wallet withdrawal (pro)
- Billing and wallet pages for both agent and pro
- adding money to wallet for agent (not sure if we handle this)
- transaction reports

Also please close https://plentific.atlassian.net/browse/PLAT-910 when you merge it. I've assigned it to you

**Comment by selinfildis** [comment]
@jose-lpa can you also review this so we merge the latest

**Review by jose-lpa — APPROVED** [review]

**Pull request merged**
